apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  namespace: kube-logging
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: do-block-storage
  gcePersistentDisk:
    pdName: elk-disk
    fsType: ext4 
